package engine

const (
	OPEN_API_VERSION          = "3.1.0"
	TITLE                     = "ApiGen"
	DESCRIPTION               = "Generated By ApiGen Package - https://github.com/hoitek-go/apigen/README.md"
	VERSION                   = "1.0.0"
	TERMS_OF_SERVICE          = "https://github.com/hoitek-go/apigen/blob/main/LICENSE"
	CONTACT_NAME              = "HoiTek"
	CONTACT_EMAIL             = "contact@hoitek.fi"
	LICENSE_NAME              = "Apache 2.0"
	LICENSE_URL               = "http://www.apache.org/licenses/LICENSE-2.0.html"
	EXTERNAL_DOCS_DESCRIPTION = "Learn More About ApiGen"
	EXTERNAL_DOCS_URL         = "https://github.com/hoitek-go/apigen/docs/start-guid.md"
)

const OPEN_API_TAG_NAME = "openapi"
const JSON_TAG_NAME = "json"

const DEFAULT_FILE_NAME = "openapi.yaml"

// slice of ignored files
var IGNORED_FILES_TO_PARS = []string{
	"_test.go",
}

const API_PATHS_DATA_REGEXP = `(@.*?)[:]\s+(.*?)\s+\*`
const API_SCHEMAS_DATA_REGEXP = `(@apiDefine)[:]\s+(.*?)\s+\*`
const API_ENUMS_DATA_REGEXP = `(@apiEnum)[:]\s+(.*?)\s+\*`
const API_CUSTOM_REF_REGEXP = `@api(\d{3})ResponseRef`
const API_CUSTOM_DESCRIPTION_REGEXP = `\w+(\d{3})ResponseDescription`

var ResponseDescriptions = map[string]string{
	"200": "OK",
	"201": "Created",
	"202": "Accepted",
	"204": "No Content",
	"400": "Bad Request",
	"401": "Unauthorized",
	"403": "Forbidden",
	"404": "Not Found",
	"405": "Method Not Allowed",
	"406": "Not Acceptable",
	"409": "Conflict",
	"410": "Gone",
	"415": "Unsupported Media Type",
	"429": "Too Many Requests",
	"500": "Internal Server Error",
}

var RestActions = map[string]string{
	"GET":    "",
	"POST":   "Create",
	"PUT":    "Update",
	"DELETE": "Delete",
}
var RestOperations = map[string]string{
	"GET":    "Query",
	"POST":   "Mutation",
	"PUT":    "Mutation",
	"DELETE": "Mutation",
}

var IgnoredDirectories = []string{
	"__pycache__",
	".git",
	".idea",
	".vscode",
	"node_modules",
	"vendor",
	"bin",
	"dist",
	"build",
	".env",
	".env.local",
	".env.dev",
	".env.prod",
	"go.mod",
	"go.sum",
	"openapi.yaml",
	".gitignore",
	"Makefile",
	"README.md",
	"LICENSE",
	"Dockerfile",
	"docker-compose.yaml",
}
